// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA0c9gj5b8PRcy-H7vu6gGQcPD6u4_pQc',
    appId: '1:888388114814:web:4c8ee14d3e144b265d7b2f',
    messagingSenderId: '888388114814',
    projectId: 'weekplan-79db1',
    authDomain: 'weekplan-79db1.firebaseapp.com',
    storageBucket: 'weekplan-79db1.firebasestorage.app',
    measurementId: 'G-7WEC7JXQF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9kEY7bUc4JIoWDA80rJ_lYXximwOyuOg',
    appId: '1:888388114814:android:9cbfd2aa4b71bdfc5d7b2f',
    messagingSenderId: '888388114814',
    projectId: 'weekplan-79db1',
    storageBucket: 'weekplan-79db1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8sEXPRNvm3OUIgZPwPpLVfKnZpRwWmcQ',
    appId: '1:888388114814:ios:43945dc30f77627b5d7b2f',
    messagingSenderId: '888388114814',
    projectId: 'weekplan-79db1',
    storageBucket: 'weekplan-79db1.firebasestorage.app',
    iosClientId: '888388114814-mjckl7jhouke5b5kle3uv7oprsopmavm.apps.googleusercontent.com',
    iosBundleId: 'com.example.weekPlan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8sEXPRNvm3OUIgZPwPpLVfKnZpRwWmcQ',
    appId: '1:888388114814:ios:43945dc30f77627b5d7b2f',
    messagingSenderId: '888388114814',
    projectId: 'weekplan-79db1',
    storageBucket: 'weekplan-79db1.firebasestorage.app',
    iosClientId: '888388114814-mjckl7jhouke5b5kle3uv7oprsopmavm.apps.googleusercontent.com',
    iosBundleId: 'com.example.weekPlan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA0c9gj5b8PRcy-H7vu6gGQcPD6u4_pQc',
    appId: '1:888388114814:web:8ff11daa91014d865d7b2f',
    messagingSenderId: '888388114814',
    projectId: 'weekplan-79db1',
    authDomain: 'weekplan-79db1.firebaseapp.com',
    storageBucket: 'weekplan-79db1.firebasestorage.app',
    measurementId: 'G-VBWLZDR7C2',
  );

}